# Generated by Django 5.0.2 on 2024-02-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_alter_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='pricipal',
            new_name='principal',
        ),
    ]
